all:
	java -cp lib/httpclient-4.1.3.jar:lib/httpcore-4.1.4.jar:lib/commons-logging-1.1.1.jar:. Client

install:
	javac -cp lib/httpclient-4.1.3.jar:lib/httpcore-4.1.4.jar:lib/commons-logging-1.1.1.jar:. Client.java
